/// action_setting_color_reset()

action_setting_color_interface(c_main)
action_setting_color_text(c_text)
action_setting_color_tips(c_tips)
action_setting_color_tips_text(c_white)
action_setting_color_buttons(c_secondary)
action_setting_color_buttons_text(c_white)
action_setting_color_boxes(c_white)
action_setting_color_boxes_text(c_text)
action_setting_color_highlight(c_highlight)
action_setting_color_highlight_text(c_white)
action_setting_color_timeline(c_white)
action_setting_color_timeline_text(c_text)
action_setting_color_alerts(c_alerts)
action_setting_color_alerts_text(c_text)
