/// project_write_timeline()
/*
buffer_write_int(iid)
buffer_write_string_int(type)
buffer_write_string_int(name)
buffer_write_int(iid_get(temp))
buffer_write_string_int(text)
buffer_write_int(color)
buffer_write_byte(lock)
buffer_write_int(depth)

buffer_write_short(bodypart)
buffer_write_int(iid_get(part_of))
buffer_write_short(part_amount)
for (var p = 0; p < part_amount; p++)
	buffer_write_int(iid_get(part[p]))

buffer_write_byte(hide)
project_write_value_types(id)
project_write_values(id)

buffer_write_int(keyframe_amount)
for (var k = 0; k < keyframe_amount; k++)
{
	with (keyframe[k])
	{
		buffer_write_int(pos)
		project_write_values(tl)
	}
}
buffer_write_int(iid_get(parent))
buffer_write_int(parent_pos)
buffer_write_byte(lock_bend)
buffer_write_byte(tree_extend)
buffer_write_byte(inherit_position)
buffer_write_byte(inherit_rotation)
buffer_write_byte(inherit_scale)
buffer_write_byte(inherit_alpha)
buffer_write_byte(inherit_color)
buffer_write_byte(inherit_texture)
buffer_write_byte(inherit_visibility)
buffer_write_byte(scale_resize)
buffer_write_byte(rot_point_custom)
buffer_write_double(rot_point[XPOS])
buffer_write_double(rot_point[YPOS])
buffer_write_double(rot_point[ZPOS])
buffer_write_byte(backfaces)
buffer_write_byte(texture_blur)
buffer_write_byte(texture_filtering)
buffer_write_byte(round_bending)
buffer_write_byte(shadows)
buffer_write_byte(ssao)
buffer_write_byte(fog)
buffer_write_byte(wind)
buffer_write_double(wind_amount)
buffer_write_byte(wind_terrain)*/
