/// @desc Define enumerators used in the project.

function enums()
{
	// Platforms
	enum e_platform
	{
		WINDOWS	= 0,
		MAC_OS	= 1,
		LINUX	= 2
	}
	
	// Project formats
	enum e_project
	{
		FORMAT_01			= 1,
		FORMAT_02			= 2,
		FORMAT_05			= 3,
		FORMAT_06			= 4,
		FORMAT_07_DEMO		= 5,
		FORMAT_100_DEMO_2	= 6,
		FORMAT_100_DEMO_3	= 7,
		FORMAT_100_DEMO_4	= 8,
		FORMAT_100_DEBUG	= 9,
		FORMAT_100			= 10,
		FORMAT_105			= 11,
		FORMAT_105_2		= 12,
		FORMAT_106			= 13,
		FORMAT_106_2		= 14,
		FORMAT_CB_100		= 20,
		FORMAT_CB_102_PRE	= 21,
		FORMAT_CB_102		= 22,
		FORMAT_CB_103		= 23,
		FORMAT_110_PRE_1	= 24,
		FORMAT_110_PRE_3	= 25,
		FORMAT_110			= 26,
		FORMAT_113			= 27,
		FORMAT_120_PRE_1	= 28,
		FORMAT_120_PRE_3	= 29,
		FORMAT_122			= 30,
		FORMAT_123_PRE_2	= 31,
		FORMAT_125			= 32,
		FORMAT_200_PRE_1	= 33,
		FORMAT_200_PRE_5	= 34,
		FORMAT_CTB_106		= 35,
		FORMAT_210			= 36
	}
	
	// Mine-imator settings format
	enum e_settings
	{
		FORMAT_100_DEMO_4	= 0,
		FORMAT_100_DEMO_5	= 1,
		FORMAT_100			= 2,
		FORMAT_103			= 3,
		FORMAT_106			= 4,
		FORMAT_106_2		= 5,
		FORMAT_106_3		= 6,
		FORMAT_CB_100		= 20,
		FORMAT_CB_102		= 22,
		FORMAT_CE_110		= 23,
		FORMAT_110_PRE_1	= 24,
		FORMAT_110			= 25,
		FORMAT_113			= 26,
		FORMAT_114			= 27,
		FORMAT_120			= 28,
		FORMAT_200			= 29
	}
	
	// Render settings format
	enum e_render_settings
	{
		FORMAT_210			= 35
	}
	
	// Key format
	enum e_key_format
	{
		FORMAT_200			= 1,
		FORMAT_210			= 2
	}
	
	// Minecraft assets .midata format
	enum e_minecraft_assets
	{
		FORMAT_110_PRE_1	= 1,
		FORMAT_110_PRE_2	= 2,
		FORMAT_113			= 3,
		FORMAT_120			= 4,
		FORMAT_123			= 5,
		FORMAT_128			= 6,
		FORMAT_129			= 7,
		FORMAT_200			= 8,
		FORMAT_201			= 9,
		FORMAT_210			= 10
	}
	
	// Minecraft resource pack
	enum e_minecraft_pack
	{
		FORMAT_161			= 1,
		FORMAT_19			= 2,
		FORMAT_111			= 3,
		FORMAT_113			= 4,
		FORMAT_115			= 5,
		
		LATEST				= 5
	}
	
	// Value types
	enum e_value_type
	{
		TRANSFORM,
		TRANSFORM_POS,
		TRANSFORM_ROT,
		TRANSFORM_SCA,
		TRANSFORM_BEND,
		TRANSFORM_PATH_POINT,
		
		MATERIAL,
		MATERIAL_TEXTURE,
		MATERIAL_COLOR,
		MATERIAL_SURFACE,
		MATERIAL_SUBSURFACE,
		
		PARTICLES,
		LIGHT,
		SPOTLIGHT,
		CAMERA,
		CAMERA_EFFECT,
		ENVIRONMENT,
		SOUND,
		TEXT,
		KEYFRAME,
		ROT_POINT,
		BLOCK,
		HIERARCHY,
		APPEARANCE,
		AUDIO,
		ITEM,
		PATH,
		amount
	}
	
	// Values
	enum e_value
	{
		POS_X,
		POS_Y,
		POS_Z,
		ROT_X,
		ROT_Y,
		ROT_Z,
		SCA_X,
		SCA_Y,
		SCA_Z,
		BEND_ANGLE_LEGACY,
		BEND_ANGLE_X,
		BEND_ANGLE_Y,
		BEND_ANGLE_Z,
		ALPHA,
		RGB_ADD,
		RGB_SUB,
		RGB_MUL,
		HSB_ADD,
		HSB_SUB,
		HSB_MUL,
		MIX_COLOR,
		GLOW_COLOR,
		MIX_PERCENT,
		EMISSIVE,
		METALLIC,
		ROUGHNESS,
		SUBSURFACE,
		SUBSURFACE_RADIUS_RED,
		SUBSURFACE_RADIUS_GREEN,
		SUBSURFACE_RADIUS_BLUE,
		SUBSURFACE_COLOR,
		WIND_INFLUENCE,
		SPAWN,
		FREEZE,
		CLEAR,
		CUSTOM_SEED,
		SEED,
		ATTRACTOR,
		FORCE,
		FORCE_DIRECTIONAL,
		FORCE_VORTEX,
		LIGHT_COLOR,
		LIGHT_STRENGTH,
		LIGHT_SPECULAR_STRENGTH,
		LIGHT_SIZE,
		LIGHT_RANGE,
		LIGHT_FADE_SIZE,
		LIGHT_SPOT_RADIUS,
		LIGHT_SPOT_SHARPNESS,
		CAM_FOV,
		CAM_SIZE_USE_PROJECT,
		CAM_SIZE_KEEP_ASPECT_RATIO,
		CAM_WIDTH,
		CAM_HEIGHT,
		CAM_ROTATE,
		CAM_ROTATE_DISTANCE,
		CAM_ROTATE_ANGLE_XY,
		CAM_ROTATE_ANGLE_Z,
		CAM_FX_SHAKE_MODE,
		CAM_FX_SHAKE_STRENGTH_X,
		CAM_FX_SHAKE_STRENGTH_Y,
		CAM_FX_SHAKE_STRENGTH_Z,
		CAM_FX_SHAKE_SPEED_X,
		CAM_FX_SHAKE_SPEED_Y,
		CAM_FX_SHAKE_SPEED_Z,
		CAM_FX_DOF_DEPTH,
		CAM_FX_DOF_RANGE,
		CAM_FX_DOF_FADE_SIZE,
		CAM_FX_DOF_BLUR_SIZE,
		CAM_FX_DOF_BLUR_RATIO,
		CAM_FX_DOF_BIAS,
		CAM_FX_DOF_THRESHOLD,
		CAM_FX_DOF_GAIN,
		CAM_FX_DOF_FRINGE,
		CAM_FX_DOF_FRINGE_ANGLE_RED,
		CAM_FX_DOF_FRINGE_ANGLE_GREEN,
		CAM_FX_DOF_FRINGE_ANGLE_BLUE,
		CAM_FX_DOF_FRINGE_RED,
		CAM_FX_DOF_FRINGE_GREEN,
		CAM_FX_DOF_FRINGE_BLUE,
		CAM_FX_BLOOM_THRESHOLD,
		CAM_FX_BLOOM_TRANSITION,
		CAM_FX_BLOOM_INTENSITY,
		CAM_FX_BLOOM_RADIUS,
		CAM_FX_BLOOM_RATIO,
		CAM_FX_BLOOM_BLEND,
		CAM_FX_BLADE_AMOUNT,
		CAM_FX_BLADE_ANGLE,
		CAM_FX_BLADE_STRETCH,
		CAM_FX_LENS_DIRT_BLOOM,
		CAM_FX_LENS_DIRT_GLOW,
		CAM_FX_LENS_DIRT_RADIUS,
		CAM_FX_LENS_DIRT_INTENSITY,
		CAM_FX_LENS_DIRT_POWER,
		CAM_FX_GRAIN_STRENGTH,
		CAM_FX_GRAIN_SATURATION,
		CAM_FX_GRAIN_SIZE,
		CAM_FX_VIGNETTE_RADIUS,
		CAM_FX_VIGNETTE_SOFTNESS,
		CAM_FX_VIGNETTE_STRENGTH,
		CAM_FX_VIGNETTE_COLOR,
		CAM_FX_CA_BLUR_AMOUNT,
		CAM_FX_CA_DISTORT_CHANNELS,
		CAM_FX_CA_RED_OFFSET,
		CAM_FX_CA_GREEN_OFFSET,
		CAM_FX_CA_BLUE_OFFSET,
		CAM_FX_DISTORT_REPEAT,
		CAM_FX_DISTORT_ZOOM_AMOUNT,
		CAM_FX_DISTORT_AMOUNT,
		CAM_FX_TONEMAPPER,
		CAM_FX_EXPOSURE,
		CAM_FX_GAMMA,
		CAM_FX_CONTRAST,
		CAM_FX_BRIGHTNESS,
		CAM_FX_SATURATION,
		CAM_FX_VIBRANCE,
		CAM_FX_COLOR_BURN,
		ENV_IMAGE_SHOW,
		ENV_IMAGE_ROTATION,
		ENV_SKY_MOON_PHASE,
		ENV_SKY_TIME,
		ENV_SKY_ROTATION,
		ENV_SUNLIGHT_STRENGTH,
		ENV_SUNLIGHT_SPECULAR_STRENGTH,
		ENV_SUNLIGHT_ANGLE,
		ENV_SKY_SUN_ANGLE,
		ENV_SKY_SUN_SCALE,
		ENV_SKY_MOON_ANGLE,
		ENV_SKY_MOON_SCALE,
		ENV_TWILIGHT,
		ENV_SKY_CLOUDS_SHOW,
		ENV_SKY_CLOUDS_SPEED,
		ENV_SKY_CLOUDS_OFFSET_Y,
		ENV_SKY_CLOUDS_OFFSET_Z,
		ENV_GROUND_SHOW,
		ENV_GROUND_SLOT,
		ENV_BIOME,
		ENV_SKY_COLOR,
		ENV_SKY_CLOUDS_COLOR,
		ENV_SUNLIGHT_COLOR,
		ENV_AMBIENT_COLOR,
		ENV_NIGHT_SKY_COLOR,
		ENV_NIGHT_SKY_CLOUDS_COLOR,
		ENV_NIGHT_SKY_STARS_COLOR,
		ENV_NIGHT_COLOR,
		ENV_GRASS_COLOR,
		ENV_FOLIAGE_COLOR,
		ENV_DRY_FOLIAGE_COLOR,
		ENV_WATER_COLOR,
		ENV_LEAVES_OAK_COLOR,
		ENV_LEAVES_SPRUCE_COLOR,
		ENV_LEAVES_BIRCH_COLOR,
		ENV_LEAVES_JUNGLE_COLOR,
		ENV_LEAVES_ACACIA_COLOR,
		ENV_LEAVES_DARK_OAK_COLOR,
		ENV_LEAVES_MANGROVE_COLOR,
		ENV_FOG_SHOW,
		ENV_FOG_SKY,
		ENV_FOG_CUSTOM_COLOR,
		ENV_FOG_COLOR,
		ENV_FOG_CUSTOM_OBJECT_COLOR,
		ENV_FOG_OBJECT_COLOR,
		ENV_FOG_DISTANCE,
		ENV_FOG_SIZE,
		ENV_FOG_HEIGHT,
		ENV_WIND,
		ENV_WIND_SPEED,
		ENV_WIND_STRENGTH,
		ENV_WIND_DIRECTION,
		ENV_WIND_DIRECTIONAL_SPEED,
		ENV_WIND_DIRECTIONAL_STRENGTH,
		ENV_TEXTURE_ANI_SPEED,
		ENV_BRIGHTNESS,
		TEXTURE_OBJ,
		TEXTURE_MATERIAL_OBJ,
		TEXTURE_NORMAL_OBJ,
		SOUND_OBJ,
		SOUND_VOLUME,
		SOUND_PITCH,
		SOUND_START,
		SOUND_END,
		TEXT,
		TEXT_FONT,
		TEXT_HALIGN,
		TEXT_VALIGN,
		TEXT_CUSTOM_ALIGNMENT,
		TEXT_OUTLINE,
		TEXT_OUTLINE_COLOR,
		TEXT_OUTLINE_SIZE,
		TEXT_CUSTOM_OUTLINE,
		CUSTOM_ITEM_SLOT,
		ITEM_SLOT,
		ITEM_NAME,
		PATH_OBJ,
		PATH_OFFSET,
		PATH_POINT_ANGLE,
		PATH_POINT_SCALE,
		IK_TARGET,
		IK_BLEND,
		IK_TARGET_ANGLE,
		IK_ANGLE_OFFSET,
		VISIBLE,
		TRANSITION,
		EASE_IN_X,
		EASE_IN_Y,
		EASE_OUT_X,
		EASE_OUT_Y,
		amount
	} // Update app_startup_lists() when adding values
	
	// Workbench tabs
	enum e_bench_tab
	{
		PROJECT,
		CHARACTER,
		EQUIPMENT,
		MODEL,
		MODEL_PART,
		ITEM,
		WORLD,
		SCHEMATIC,
		BLOCK,
		SPECIAL_BLOCK,
		CAMERA,
		SOUND,
		AUDIO_TRACK,
		PARTICLE_SPAWNER,
		TEXT,
		LIGHT_SOURCE,
		CAMERA_EFFECT,
		PATH,
		ENVIRONMENT,
		SHAPE,
		amount
	}
	
	// Workbench example images
	enum e_bench_example
	{
		WORLD,
		CAMERA,
		AUDIO_TRACK,
		CAMERA_EFFECT,
		FADE,
		CAMERA_SHAKE,
		DEPTH_OF_FIELD,
		BLOOM,
		LENS_DIRT,
		FILM_GRAIN,
		VIGNETTE,
		CHROMATIC_ABERRATION,
		DISTORT,
		LIGHT_MANAGEMENT,
		POINT_LIGHT,
		SPOT_LIGHT,
		PATH,
		ENVIRONMENT		
	}
	
	// Workbench buttons
	enum e_bench_button
	{
		CREATE,
		EDIT,
		CREATE_AND_EDIT,
		START_BUILDING
	}
	
	// Template types
	enum e_temp_type
	{
		CHARACTER,
		EQUIPMENT,
		MODEL,
		MODEL_PART,
		ITEM,
		SCENERY,
		BLOCK,
		SPECIAL_BLOCK,
		PARTICLE_SPAWNER,
		TEXT,
		CUBE,
		CONE,
		CYLINDER,
		SPHERE,
		SURFACE,
		amount
	} // Update app_startup_lists() when adding types
	
	// Timeline types
	enum e_tl_type
	{
		CHARACTER,
		EQUIPMENT,
		MODEL,
		MODEL_PART,
		ITEM,
		SCENERY,
		BLOCK,
		SPECIAL_BLOCK,
		PARTICLE_SPAWNER,
		TEXT,
		CUBE,
		CONE,
		CYLINDER,
		SPHERE,
		SURFACE,
		CAMERA,
		CAMERA_EFFECT,
		AUDIO_TRACK,
		POINT_LIGHT,
		SPOT_LIGHT,
		PATH,
		PATH_POINT,
		ENVIRONMENT,
		STRUCTURE,
		FOLDER,
		amount
	} // Update app_startup_lists() when adding types
	
	// Resource types
	enum e_res_type
	{
		PACK,
		PACK_UNZIPPED,
		SKIN,
		DOWNLOADED_SKIN,
		MODEL,
		ITEM_SHEET,
		FROM_WORLD,
		SCHEMATIC,
		BLOCK_SHEET,
		LEGACY_BLOCK_SHEET,
		SOUND,
		PARTICLE_SHEET,
		FONT,
		TEXTURE,
		amount
	} // Update app_startup_lists() when adding types
	
	// Camera effect types
	enum e_cam_fx
	{
		 FADE,
		 SHAKE,
		 DOF,
		 BLOOM,
		 LENS_DIRT,
		 GRAIN,
		 VIGNETTE,
		 CA,
		 DISTORT,
		 LIGHT_MANAGEMENT,
		 COLOR_CORRECTION,
		 amount
	}

	// Shape types
	enum e_shape_type
	{
		CUBE,
		CONE,
		CYLINDER,
		SPHERE,
		SURFACE,
		amount
	}
	
	// Model format
	enum e_model_format
	{
		MIMODEL,
		BLOCK
	}
	
	// Timeline parent action
	enum e_parent_action
	{
		TARGET,
		BEND,
		POS,
		ROT,
		SCA,
		LOCK
	}

	// Icons
	enum icons
	{
		ALIGN_BOTTOM,
		ALIGN_CENTER,
		ALIGN_LEFT,
		ALIGN_MIDDLE,
		ALIGN_RIGHT,
		ALIGN_TOP,
		ANNOUNCEMENT,
		ARROW_DOWN,
		ARROW_LEFT,
		ARROW_RIGHT,
		ARROW_UP,
		ASSET,
		ASSET_ADD,
		ASSET_EXPORT,
		ASSET_IMPORT,
		ASSET_INSTANCE,
		ASSET_LIST,
		AWARDS_RECENT,
		BACK,
		BEAKER,
		BELL,
		BELL_SLASH,
		BEND,
		BEND_SHARP,
		BEND_SMALL,
		BETA,
		BIRTHDAY,
		BLOCK,
		BLOCK_SPECIAL,
		BOLD,
		BOUNDARY_BOX,
		BOUNDARY_CIRCLE,
		BOUNDARY_CUBE,
		BOX_SELECT,
		BROOM,
		BRUSH,
		BRUSH_SMALL,
		BUG,
		CALENDAR,
		CAMERA,
		CAMERA_ACTIVE,
		CAMERA_PHOTO,
		CAMERA_PHOTO_SMALL,
		CAMERA_SMALL,
		CARDS,
		CHARACTER,
		CHARACTER_PARTS,
		CHECKBOX_INDETERMINATE,
		CHECKBOX_TICK,
		CHEVRON_DOWN,
		CHEVRON_DOWN_TINY,
		CHEVRON_LEFT,
		CHEVRON_LEFT_TINY,
		CHEVRON_RIGHT,
		CHEVRON_RIGHT_TINY,
		CHEVRON_UP,
		CHEVRON_UP_TINY,
		CIRCLE,
		CIRCLE_OUTLINE,
		CLAPPERBOARD,
		CLAPPERBOARD_SMALL,
		CLEAR_FORMAT,
		CLICK_LEFT,
		CLICK_MIDDLE,
		CLICK_RIGHT,
		CLOCK,
		CLOSE,
		CLOSE_SMALL,
		CLOUD,
		CLOUD_ACTIVE,
		CODE,
		COMMENT,
		COMMENTS,
		COMPACT,
		CONE,
		CONE_DARK,
		CONTENT,
		COPY,
		COPY_ALL,
		COPY_KEYFRAME,
		COPY_SMALL,
		CROWN,
		CUBE,
		CUBE_DARK,
		CUBE_ADD,
		CUSTOMIZATION,
		CUT,
		CUT_ALL,
		CUT_KEYFRAME,
		CYLINDER,
		CYLINDER_DARK,
		DASHBOARD,
		DELETE,
		DELETE_KEYFRAME,
		DELETE_SELECTION,
		DISCORD,
		DONATE,
		DOT,
		DOWNLOAD,
		DRAG_LEFT,
		DRAG_MIDDLE,
		DRAG_RIGHT,
		DRAGGER,
		DUPLICATE,
		DUPLICATE_SELECTION,
		DUSK,
		EASE_BACK,
		EASE_BOUNCE,
		EASE_CIRCULAR,
		EASE_CUBIC,
		EASE_CUSTOM,
		EASE_ELASTIC,
		EASE_EXPONENTIAL,
		EASE_IN,
		EASE_IN_OUT,
		EASE_INSTANT,
		EASE_LINEAR,
		EASE_OUT,
		EASE_QUAD,
		EASE_QUART,
		EASE_QUINT,
		EASE_SINE,
		ELLIPSIS_HORIZONTAL,
		ELLIPSIS_VERTICAL,
		EMOJI,
		ENVELOPE,
		EXIT,
		EXTERNAL,
		FILE,
		FILE_ADD,
		FILE_EXPORT,
		FILE_IMPORT,
		FILE_OBJ,
		FILE_SMALL,
		FILE_TEMPLATE,
		FILTER,
		FIRE,
		FIREWORKS,
		FLAG,
		FOLDER,
		FOLDER_ADD,
		FOLDER_EDIT,
		FOLDER_IMPORT,
		FOLDER_RECENTS,
		FOLLOWED,
		FOLLOWED_SETTINGS,
		FORUM_STATS,
		FORWARD,
		FRAME_NEXT,
		FRAME_PREVIOUS,
		GAME,
		GHOST,
		GHOST_SMALL,
		GIMBAL,
		GOOSE,
		GRID,
		GROUP,
		HAMMER,
		HEART,
		HEART_BROKEN,
		HELP,
		HELP_CIRCLE,
		HIDDEN,
		HIDDEN_SMALL,
		HIERARCHY,
		HIERARCHY_SMALL,
		HIGHLIGHTER,
		HISTORIAN,
		HOUSE,
		IGNORE,
		IMAGE,
		IMAGE_EXPORT,
		IMAGE_EXPORT_SMALL,
		INFO,
		INTERNAL,
		ITALICS,
		ITEM,
		ITEM_SMALL,
		JOINT,
		JOINT_SMALL,
		KEY,
		KEYBOARD,
		KEYBOARD_SMALL,
		KEYFRAME,
		KEYFRAME_FILLED,
		KEYFRAME_FILLED_SMALL,
		KEYFRAME_INSTANT,
		KEYFRAME_INSTANT_FILLED,
		KEYFRAME_INSTANT_FILLED_SMALL,
		KEYFRAME_INSTANT_SMALL,
		KEYFRAME_NEXT,
		KEYFRAME_PREVIOUS,
		KEYFRAME_SMALL,
		LAPTOP,
		LETTERBOX,
		LIBRARY,
		LIBRARY_SMALL,
		LIGHT_OMNI,
		LIGHT_POINT,
		LIGHT_POINT_SMALL,
		LIGHT_SPOT,
		LIGHTBULB,
		LINK,
		LINK_REMOVE,
		LINK_SMALL,
		LIST_BULLETED_LTR,
		LIST_BULLETED_RTL,
		LIST_BULLETED_SMALL,
		LIST_NUMBERED_LTR,
		LIST_NUMBERED_RTL,
		LOCK,
		LOCK_SMALL,
		LOGOUT,
		LOUNGE,
		MAGNET,
		MANUAL,
		MARK,
		MARKER,
		MARKER_ADD,
		MAXIMIZE,
		MEDAL,
		MENU,
		MERGE,
		MINIMIZE,
		MIRROR_HORIZONTALLY,
		MIRROR_VERTICALLY,
		MOBILE,
		MODEL,
		MODEL_SMALL,
		MOON,
		MOVE,
		MOVIE,
		MOVIE_EXPORT,
		MULTITRANSFORM,
		MUTE,
		MUTE_SMALL,
		NEWSPAPER,
		NOTE,
		NOTE_SMALL,
		OVERLAYS,
		PALETTE,
		PAN,
		PART,
		PART_ADD,
		PART_IMPORT,
		PARTICLES,
		PARTICLES_SMALL,
		PASTE,
		PASTE_ALL,
		PASTE_FORMAT,
		PASTE_KEYFRAME,
		PASTE_SMALL,
		PATH,
		PATH_POINT,
		PATH_SMALL,
		PAUSE,
		PENCIL,
		PERSON,
		PERSON_ADD,
		PERSON_CLOSE,
		PERSON_EDIT,
		PERSON_ONLINE,
		PERSON_RECENTS,
		PERSON_SETTINGS,
		PERSON_STATS,
		PERSON_TICK,
		PHI,
		PICKER,
		PICKER_SMALL,
		PILLARBOX,
		PIN,
		PIN_SMALL,
		PIVOT,
		PLANE,
		PLANE_3D,
		PLANE_3D_DARK,
		PLANE_3D_ADD,
		PLANE_ADD,
		PLAYER,
		PLAY,
		PLAY_REGION,
		PLUS,
		POLL,
		POSING,
		POST_RECENTS,
		PROGRAM_SETTINGS,
		PUPPETRY,
		QUALITY,
		QUOTE,
		RANDOMIZE,
		RECENTS,
		RECENTS_REMOVE,
		REDO,
		REFRESH,
		RELOAD,
		RENAME,
		REPEAT,
		REPEAT_SEAMLESS,
		REPLACE,
		REPLY,
		RESET,
		RESET_ALL,
		RESET_SMALL,
		ROCKETSHIP,
		ROTATE,
		ROTATE_180,
		ROTATE_CCW,
		ROTATE_CW,
		RUN_CYCLE,
		SAVE,
		SAVE_AS,
		SAVE_KEYFRAME,
		SCALE,
		SCENERY,
		SCENERY_EDIT,
		SCROLL,
		SEARCH,
		SELECT,
		SELECT_ALL,
		SELECT_ALL_KEYFRAME,
		SEND,
		SETTINGS,
		SETTINGS_EXPORT,
		SETTINGS_IMPORT,
		SETTINGS_SETDEFAULT,
		SETTINGS_SMALL,
		SHAPES,
		SHARE,
		SHIELD,
		SLIDERS,
		SORT_DOWN,
		SORT_UP,
		SPHERE,
		SPHERE_DARK,
		SPHERE_MATERIAL,
		SPHERE_MATERIAL_DARK,
		SPHERE_MATERIAL_SMALL,
		SPHERE_MATERIAL_SMALL_DARK,
		SPHERE_SHADING,
		SPHERE_SHADING_DARK,
		SPHERE_SHADING_SMALL,
		SPHERE_SHADING_SMALL_DARK,
		SPHERE_TEXTURE,
		SPLIT_CORNER,
		SPLIT_HORIZONTAL,
		SPLIT_VERTICAL,
		STAR,
		STOP,
		STOPWATCH,
		STRIKETHROUGH,
		SUN,
		TAG,
		TAG_ADD,
		TAG_REMOVE,
		TEXT,
		TEXT_ALIGN_CENTER,
		TEXT_ALIGN_LEFT,
		TEXT_ALIGN_RIGHT,
		TEXT_COLOR,
		TEXT_SMALL,
		TEXTURE,
		TEXTURE_EXPORT,
		TEXTURE_SMALL,
		TICK,
		TORUS,
		TORUS_DARK,
		TRANSFORM,
		TRANSFORM_SMALL,
		TRANSFORMATION_GIMBAL,
		TRANSFORMATION_GLOBAL,
		TRANSFORMATION_LOCAL,
		TROPHY,
		TUTORIALS,
		TWITTER,
		UNDERLINE,
		UNDO,
		UNLOCK,
		UNLOCK_SMALL,
		UNMARK,
		UNREAD,
		VCARD,
		VIEW_GRID,
		VIEW_LIST,
		VIEWPORT_SECONDARY,
		VISIBLE,
		VISIBLE_SMALL,
		VOLUME,
		VOLUME_SMALL,
		WALK,
		WALK_CYCLE,
		WAND,
		WARNING_CIRCLE,
		WARNING_DIAMOND,
		WARNING_TRIANGLE,
		WAVE,
		WEB,
		WIND,
		WIND_SMALL,
		WORKBENCH,
		WORLD,
		WORLD_SMALL,
		YOUTUBE,
		ZOOM_IN,
		ZOOM_OUT
	}
	
	// Renderer
	enum e_renderer
	{
		QUICK,
		STANDARD,
		REALISTIC,
		COMMON
	}
	
	// Render modes
	enum e_render_mode
	{
		CLICK,
		SELECT,
		PLACE_SELECT,
		PLACE_PARENT,
		PREVIEW,
		COLOR,
		COLOR_FOG,
		COLOR_FOG_LIGHTS,
		ALPHA_FIX,
		ALPHA_TEST,
		DEPTH,
		HIGH_LIGHT_SUN_DEPTH,
		HIGH_LIGHT_SPOT_DEPTH,
		HIGH_LIGHT_POINT_DEPTH,
		HIGH_LIGHT_SUN,
		HIGH_LIGHT_SPOT,
		HIGH_LIGHT_POINT,
		HIGH_LIGHT_POINT_SHADOWLESS,
		HIGH_FOG,
		SCENE_TEST,
		G_BUFFERS,
		AUXILIARY,
		PLACE
	}
	
	// Shader uniforms
	enum e_uniform
	{
		AA_MATRIX,
		ADD_TEXEL_SIZE,
		AFFECT_ALPHA,
		ALPHA_HASH,
		AMBIENT_COLOR,
		AMOUNT,
		AREA_SAMPLES,
		BACKGROUND_BRIGHTNESS,
		BIAS,
		BLADE_AMOUNT,
		BLADE_ROTATION,
		BLADE_ROUNDING,
		BLADE_STRETCH,
		BLEND_COLOR,
		BLUR_AMOUNT,
		BLUR_RATIO,
		BLUR_SIZE,
		BOX,
		BRIGHTNESS,
		CAMERA_DEPTH,
		CAMERA_POS,
		CAMERA_POSITION,
		CASCADE_COUNT,
		CASCADE_END_CLIP_SPACE,
		CASCADE_WORLD_SIZE,
		CHANNEL,
		CLAMP_EDGES,
		CLIP_BOX,
		CLIP_ENABLED,
		COLOR,
		COLOR_BURN,
		COLOR_OFFSET,
		COLORS_EXT,
		CONTRAST,
		DEFAULT_EMISSIVE,
		DEFAULT_SUBSURFACE,
		DEPTH,
		DEPTH_BUFFER_SIZE,
		DIRECTION,
		DISTORT_AMOUNT,
		DISTORT_CHANNELS,
		EMISSIVE,
		EXPOSURE,
		EYE,
		FADE_AMOUNT,
		FADE_SIZE,
		FALLBACK_COLOR,
		FALLBACK_ONLY,
		FAR,
		FOG,
		FOG_APPLY,
		FOG_COLOR,
		FOG_DISTANCE,
		FOG_ENABLED,
		FOG_HEIGHT,
		FOG_SHOW,
		FOG_SIZE,
		FRINGE,
		FRINGE_OFFSET_BLUE,
		FRINGE_OFFSET_GREEN,
		FRINGE_OFFSET_RED,
		GAIN,
		GAMMA,
		GLINT_ENABLED,
		GLINT_OFFSET,
		GLINT_SIZE,
		GLINT_STRENGTH,
		GLOW,
		GLOW_PASS,
		GLOW_COLOR,
		GLOW_TEXTURE,
		GM_DEPTH,
		HAS_NORMAL_MAP,
		HSB_ADD,
		HSB_MUL,
		HSB_SUB,
		INDIRECT_ENABLED,
		INDIRECT_STRENGTH,
		IS_BLOCK,
		IS_GROUND,
		IS_SKY,
		IS_WATER,
		KERNEL,
		LIGHT_AMOUNT,
		LIGHT_COLOR,
		LIGHT_DATA,
		LIGHT_DIRECTION,
		LIGHT_FADE_SIZE,
		LIGHT_FAR,
		LIGHT_MAT_BIAS_MVP,
		LIGHT_MATRIX,
		LIGHT_NEAR,
		LIGHT_POSITION,
		LIGHT_REALISTIC_FALLOFF,
		LIGHT_SIZE,
		LIGHT_SPECULAR,
		LIGHT_SPOT_SHARPNESS,
		LIGHT_STRENGTH,
		LINE_LENGTH,
		MASK,
		MATERIAL_FORMAT,
		METALLIC,
		MIX_COLOR,
		NEAR,
		NOISE_SIZE,
		ONLY_RENDER_GLOW,
		OUTLINE_SIZE,
		PCSS_KERNEL,
		PALETTE_SIZE,
		PIXEL_CHECK,
		PIXEL_ROTATION,
		POWER,
		PRECISION,
		PREVIOUS_AMOUNT,
		PROJ_MATRIX,
		PROJ_MATRIX_INV,
		RGB_ADD,
		RGB_SUB,
		RADIUS,
		RANGE,
		RAY_DATA_SIZE,
		RAY_DIRECTION,
		RAY_DISTANCE,
		REFLECTIONS_ENABLED,
		RENDER_BACKGROUND,
		REPEAT_IMAGE,
		REPLACE_COLOR,
		ROUGHNESS,
		SSAO,
		SSAO_ALWAYS_VISIBLE,
		SSAO_ENABLED,
		SSS,
		SSS_BACKLIGHT_SPREAD,
		SSS_BACKLIGHT_STRENGTH,
		SSS_BRIGHT_BACKLIGHT,
		SSS_COLOR,
		SSS_RADIUS,
		SAMPLE_AMOUNT,
		SAMPLE_INDEX,
		SAMPLES,
		SAMPLES_STRENGTH,
		SATURATION,
		SCREEN_SIZE,
		SHADOW_BLUR_QUALITY,
		SHADOW_MATRIX,
		SHADOW_POSITION,
		SHADOW_RADIUS,
		SHADOWS_ENABLED,
		SIZE,
		SKY_COLOR,
		SOFTNESS,
		SPECULAR_ENABLED,
		STRENGTH,
		SUN_ANGULAR_RADIUS,
		SUN_DIRECTION,
		SUN_FAR,
		SUN_NEAR,
		SUN_SHADOW_SCALE,
		TAA_MATRIX,
		TENT_FILTER,
		TEX_SIZE,
		TEXTURE_OFFSET,
		TEXTURE_SIZE,
		THICKNESS,
		THRESHOLD,
		TIME,
		TONEMAPPER,
		TRANSITION,
		VIBRANCE,
		VIEW_MATRIX_INV,
		VIEWPORT_SIZE,
		WATER_MATERIAL_OCTAVES,
		WATER_MATERIAL_SCALE,
		WATER_MATERIAL_STRENGTH,
		WATER_MATERIAL_TIME,
		WEIGHT_SAMPLES,
		WIND_DIRECTION,
		WIND_DIRECTIONAL_SPEED,
		WIND_DIRECTIONAL_STRENGTH,
		WIND_ENABLE,
		WIND_SPEED,
		WIND_STRENGTH,
		WIND_TERRAIN,
		ZOOM_AMOUNT,
		amount
	} // Update shader_startup_uniforms() when adding uniforms

	// Anti-aliasing
	enum e_aa_mode
	{
		PROGRESSIVE,
		FXAA
	}
	
	// Menus
	enum e_menu
	{
		LIST,
		LIST_SEAMLESS,
		TIMELINE,
		BIOME,
		TRANSITION_LIST,
		CONTENT
	}
	
	// Buttons
	enum e_button
	{
		PRIMARY,
		SECONDARY,
		TERTIARY,
		TOOLBAR,
		MEDIUM,
		BIG,
		
		NO_TEXT,
		TEXT,
		CAPTION,
		LABEL
	}
	
	// Input box types
	enum e_inputbox
	{
		LEFT,
		RIGHT,
		BIG
	}
	
	// Button anchor
	enum e_anchor
	{
		LEFT,
		CENTER,
		RIGHT
	}
	
	// Options
	enum e_option
	{
		BROWSE					= -10,
		IMPORT_WORLD			= -11,
		DOWNLOAD_SKIN			= -12,
		DOWNLOAD_SKIN_DONE		= -13,
		IMPORT_ITEM_SHEET_DONE	= -14
	}
	
	// Directions
	enum e_dir
	{
		EAST,
		WEST,
		SOUTH,
		NORTH,
		UP,
		DOWN,
		amount
	}
	
	// Parts
	enum e_part
	{
		RIGHT,
		LEFT,
		FRONT,
		BACK,
		UPPER,
		LOWER,
		amount
	}
	
	// Bend
	enum e_bend
	{
		FORWARD,
		BACKWARD,
		BOTH
	}
	
	// Scrollbar
	enum e_scroll
	{
		VERTICAL,
		HORIZONTAL
	}

	// Item sheet
	enum e_item_sheet
	{
		SIZE16,
		SIZE32,
		amount
	}

	// Block sheet
	enum e_block_sheet
	{
		STATIC16,
		STATIC32,
		STATIC64,
		ANIMATED,
		amount,
		static_amount = 3
	}
	
	// Buffer depth
	enum e_block_depth
	{
		DEPTH0, // Opaque
		DEPTH1, // Transparent
		DEPTH2, // Semi-transparent
		amount
	}
	
	// Buffers
	enum e_block_vbuffer
	{
		STATIC16,
		STATIC32,
		STATIC64,
		ANIMATED,
		GRASS,
		FOLIAGE,
		DRY_FOLIAGE,
		LEAVES_OAK,
		LEAVES_SPRUCE,
		LEAVES_BIRCH,
		LEAVES_JUNGLE,
		LEAVES_ACACIA,
		LEAVES_DARK_OAK,
		LEAVES_MANGROVE,
		WATER,
		amount
	}
	
	// Vertex wave
	enum e_vertex_wave
	{
		NONE,
		Z_ONLY,
		ALL,
	}
	
	// NBT
	enum e_nbt
	{
		TAG_END			= 0,
		TAG_BYTE		= 1,
		TAG_SHORT		= 2,
		TAG_INT			= 3,
		TAG_LONG		= 4,
		TAG_FLOAT		= 5,
		TAG_DOUBLE		= 6,
		TAG_BYTE_ARRAY	= 7,
		TAG_STRING		= 8,
		TAG_LIST		= 9,
		TAG_COMPOUND	= 10,
		TAG_INT_ARRAY	= 11,
		TAG_LONG_ARRAY	= 12,
		amount
	}
	
	// Toasts
	enum e_toast
	{
		INFO,
		POSITIVE,
		WARNING,
		NEGATIVE
	}
	
	// Viewport tools
	enum e_view_tool
	{
		SELECT,
		MOVE,
		ROTATE,
		SCALE,
		BEND,
		TRANSFORM,
		amount
	}
	
	// View control
	enum e_view_control
	{
		POS_X,
		POS_Y,
		POS_Z,
		POS_XY,
		POS_XZ,
		POS_YZ,
		POS_PAN,
		
		ROT_X,
		ROT_Y,
		ROT_Z,
		
		SCA_X,
		SCA_Y,
		SCA_Z,
		SCA_XY,
		SCA_XZ,
		SCA_YZ,
		SCA_XYZ,
		
		BEND_X,
		BEND_Y,
		BEND_Z,
		
		ROT_ANGLE_XY,
		ROT_ANGLE_Z,
		ROT_DISTANCE
	}
	
	// Mouse controls
	enum e_mouse
	{
		CLICK_LEFT,
		CLICK_MIDDLE,
		CLICK_RIGHT,
		DRAG_LEFT,
		DRAG_MIDDLE,
		DRAG_RIGHT,
		SCROLL
	}
	
	// Render passes
	enum e_render_pass
	{
		COMBINED,
		DEPTH,
		NORMAL,
		MATERIAL,
		DIFFUSE,
		SPECULAR,
		AO,
		SHADOWS,
		INDIRECT,
		INDIRECT_SHADOWS,
		REFLECTIONS,
		FOG,
		MASK,
		GLOW,
		SUBSURFACE,
		SUBSURFACE_RANGE,
		EMISSIVE,
		ROUGHNESS,
		METALLIC,
		FRESNEL,
		SSAO_MASK,
		BLOOM_THRESHOLD,
		BLOOM_BLUR,
		ALL,
		amount
	}

	// Texture resource channels
	enum e_texture_channel
	{
		DIFFUSE,
		MATERIAL,
		NORMAL,
		amount
	}
	
	// Biome color
	enum e_biome_color
	{
		GRASS,
		FOLIAGE,
		DRY_FOLIAGE,
		WATER,
		LEAVES_OAK,
		LEAVES_SPRUCE,
		LEAVES_BIRCH,
		LEAVES_JUNGLE,
		LEAVES_ACACIA,
		LEAVES_DARK_OAK,
		LEAVES_MANGROVE,
		amount
	}
	
	// Material map format
	enum e_material
	{
		FORMAT_NONE,
		FORMAT_SEUS,
		FORMAT_LABPBR
	}
	
	// Glint mode
	enum e_glint
	{
		NONE, // Legacy
		ITEM,
		ARMOR
	}
	
	// Alpha mode
	enum e_alpha_mode
	{
		BLEND,
		HASHED,
		DEFAULT
	}
	
	// Tonemapper
	enum e_tonemapper
	{
		NONE,
		REINHARD,
		ACES,
		UCHIMURA,
		LOTTES,
		HABLE,
		GT7_CURVE,
		PBR_NEUTRAL,
		AGX,
		AGX_PUNCHY
	}
	
	// Window
	enum e_window
	{
		MAIN,
		VIEW_SECOND,
		TIMELINE
	}
	
	// Taskbar progress state
	enum e_window_taskbar_state
	{
		NOPROGRESS		= 0,
		INDETERMINATE	= 1,
		NORMAL			= 2,
		ERROR			= 4,
		PAUSED			= 8
	}
	
	// Context menu type
	enum e_context_type
	{
		NONE,
		NUMBER,
		STRING,
		BOOLEAN,
		COLOR,
		TIME
	}
	
	// Context menu group
	enum e_context_group
	{
		ROT_POINT,
		POSITION,
		ROTATION,
		SCALE,
		BEND,
		LIGHT,
		COLOR,
		CAMERA,
		EASE,
		amount
	}
	
	// JSON character
	enum e_json_char
	{
		CURLY_BEGIN		= ord("{"),
		CURLY_END		= ord("}"),
		SQUARE_BEGIN	= ord("["),
		SQUARE_END		= ord("]"),
		COMMA			= ord(","),
		COLON			= ord(":"),
		QUOTE			= ord("\""),
		SPACE			= ord(" "),
		TAB				= ord("\t"),
		NEW_LINE		= ord("\n"),
		RETURN			= ord("\r"),
		POINT			= ord("."),
		MINUS			= ord("-"),
		PLUS			= ord("+"),
		BACKSLASH		= ord("\\"),
		E				= ord("e"),
		CAPITAL_E		= ord("E"),
		F				= ord("f"),
		N				= ord("n"),
		T				= ord("t"),
		U				= ord("u"),
		NUM_0			= ord("0"),
		NUM_9			= ord("9")
	}
	
	// JSON type
	enum e_json_type
	{
		NUMBER,
		STRING,
		BOOL,
		NULL,
		ARRAY,
		OBJECT
	}
	
	// Recent projects
	enum e_recent_sort 
	{
		DATE_NEWEST,
		DATE_OLDEST,
		NAME_A_Z,
		NAME_Z_A
	}
	
	// Micro animation
	enum e_microani
	{
		HOVER,
		RADIO_HOVER,
		PRESS,
		ACTIVE,
		DISABLED,
		CUSTOM,
		FADE,
		HOVER_LINEAR,
		RADIO_HOVER_LINEAR,
		PRESS_LINEAR,
		ACTIVE_LINEAR,
		DISABLED_LINEAR,
		CUSTOM_LINEAR,
		FADE_LINEAR,
		GOAL_EASE
	}
	
	// Keybind key
	enum e_keybind_key
	{
		CHAR,
		CTRL,
		SHIFT,
		ALT
	}
	
	// Keybind
	enum e_keybind
	{
		// File
		PROJECT_NEW,
		PROJECT_OPEN,
		PROJECT_SAVE,
		PROJECT_SAVE_AS,
		IMPORT_ASSET,
		
		// Editing
		UNDO,
		REDO,
		TIMELINE_DELETE,
		TIMELINE_DUPLICATE,
		TIMELINE_SELECT,
		CREATE_FOLDER,
		KEYFRAMES_CREATE,
		KEYFRAMES_COPY,
		KEYFRAMES_CUT,
		KEYFRAMES_PASTE,
		KEYFRAMES_DELETE,
		KEYFRAMES_STRETCH,
		KEYFRAMES_SCALE,
		TIMELINE_HIDE,
		TIMELINE_SHOW_HIDDEN,
		
		// Timeline
		PLAY,
		PLAY_STOP,
		PLAY_BEGINNING,
		MARKER_RIGHT,
		MARKER_LEFT,
		FRAME_PREVIOUS,
		FRAME_NEXT,
		
		// Viewport
		RENDER_MODE,
		SECONDARY_VIEW,
		PARTICLES_SPAWN,
		PARTICLES_CLEAR,
		
		// Tools
		WORKBENCH,
		BUILD_TOOL,
		TOOL_SELECT,
		TOOL_MOVE,
		TOOL_ROTATE,
		TOOL_SCALE,
		TOOL_BEND,
		TOOL_TRANSFORM,
		SNAP,
		
		// Navigation
		CAM_FORWARD,
		CAM_BACK,
		CAM_LEFT,
		CAM_RIGHT,
		CAM_ASCEND,
		CAM_DESCEND,
		CAM_ROLL_FORWARD,
		CAM_ROLL_BACK,
		CAM_RESET,
		CAM_ROLL_RESET,
		CAM_FAST,
		CAM_SLOW,
		CAM_VIEW_TIMELINE,
		
		amount
	}
}
