/// settings_read_colors()

setting_color_interface = buffer_read_int()               debug("setting_color_interface", setting_color_interface)
setting_color_background = buffer_read_int()              debug("setting_color_background", setting_color_background)
setting_color_background_scrollbar = buffer_read_int()    debug("setting_color_background_scrollbar", setting_color_background_scrollbar)
setting_color_text = buffer_read_int()                    debug("setting_color_text", setting_color_text)
setting_color_tips = buffer_read_int()                    debug("setting_color_tips", setting_color_tips)
setting_color_tips_text = buffer_read_int()               debug("setting_color_tips_text", setting_color_tips_text)
setting_color_buttons = buffer_read_int()                 debug("setting_color_buttons", setting_color_buttons)
setting_color_buttons_pressed = buffer_read_int()         debug("setting_color_buttons_pressed", setting_color_buttons_pressed)
setting_color_buttons_text = buffer_read_int()            debug("setting_color_buttons_text", setting_color_buttons_text)
setting_color_boxes = buffer_read_int()                   debug("setting_color_boxes", setting_color_boxes)
setting_color_boxes_pressed = buffer_read_int()           debug("setting_color_boxes_pressed", setting_color_boxes_pressed)
setting_color_boxes_text = buffer_read_int()              debug("setting_color_boxes_text", setting_color_boxes_text)
setting_color_highlight = buffer_read_int()               debug("setting_color_highlight", setting_color_highlight)
setting_color_highlight_text = buffer_read_int()          debug("setting_color_highlight_text", setting_color_highlight_text)
setting_color_timeline = buffer_read_int()                debug("setting_color_timeline", setting_color_timeline)
setting_color_timeline_text = buffer_read_int()           debug("setting_color_timeline_text", setting_color_timeline_text)
setting_color_timeline_select = buffer_read_int()         debug("setting_color_timeline_select", setting_color_timeline_select)
setting_color_alerts = buffer_read_int()                  debug("setting_color_alerts", setting_color_alerts)
setting_color_alerts_text = buffer_read_int()             debug("setting_color_alerts_text", setting_color_alerts_text)
