function project_save_environment()
{
	json_save_object_start("environment")
		
		json_save_var("dimension", env_dimension)

		json_save_var_bool("image_show", env_background_image_show)
		json_save_var_save_id("image", env_background_image)
		json_save_var("image_type", env_background_image_type)
		json_save_var_bool("image_stretch", env_background_image_stretch)
		json_save_var_bool("image_box_mapped", env_background_image_box_mapped)
		json_save_var("image_rotation", env_background_image_rotation)
		
		json_save_var_save_id("sky_sun_tex", env_sky_sun_tex)
		json_save_var("sky_sun_angle", env_sky_sun_angle)
		json_save_var("sky_sun_scale", env_sky_sun_scale)
		json_save_var_save_id("sky_moon_tex", env_sky_moon_tex)
		json_save_var("sky_moon_phase", env_sky_moon_phase)
		json_save_var("sky_moon_angle", env_sky_moon_angle)
		json_save_var("sky_moon_scale", env_sky_moon_scale)
		
		json_save_var("sky_time", env_sky_time)
		json_save_var("sky_rotation", env_sky_rotation)
		json_save_var("sunlight_strength", env_sunlight_strength)
		json_save_var("sunlight_specular_strength", env_sunlight_specular_strength)
		json_save_var("sunlight_angle", env_sunlight_angle)
		
		json_save_var_bool("twilight", env_twilight)
		
		json_save_var_bool("sky_clouds_show", env_sky_clouds_show)
		json_save_var("sky_clouds_mode", env_sky_clouds_mode)
		json_save_var_save_id("sky_clouds_tex", env_sky_clouds_tex)
		json_save_var("sky_clouds_speed", env_sky_clouds_speed)
		json_save_var("sky_clouds_offset_y", env_sky_clouds_offset_y)
		json_save_var("sky_clouds_offset_z", env_sky_clouds_offset_z)
		json_save_var("sky_clouds_size_xy", env_sky_clouds_size_xy)
		json_save_var("sky_clouds_size_z", env_sky_clouds_size_z)
		
		json_save_var_bool("ground_show", env_ground_show)
		json_save_var("ground_name", env_ground_name)
		json_save_var_save_id("ground_tex", env_ground_tex)
		json_save_var_save_id("ground_tex_material", env_ground_tex_material)
		json_save_var_save_id("ground_tex_normal", env_ground_tex_normal)
		
		json_save_var("biome", env_biome)
		
		json_save_var_color("sky_color", env_sky_color)
		json_save_var_color("sky_clouds_color", env_sky_clouds_color)
		json_save_var_color("sunlight_color", env_sunlight_color)
		json_save_var_color("ambient_color", env_ambient_color)
		json_save_var_color("night_sky_color", env_night_sky_color)
		json_save_var_color("night_sky_clouds_color", env_night_sky_clouds_color)
		json_save_var_color("night_sky_stars_color", env_night_sky_stars_color)
		json_save_var_color("night_color", env_night_color)
		
		json_save_var_color("grass_color", env_grass_color)
		json_save_var_color("foliage_color", env_foliage_color)
		json_save_var_color("dry_foliage_color", env_dry_foliage_color)
		json_save_var_color("water_color", env_water_color)
		json_save_var_color("leaves_oak_color", env_leaves_oak_color)
		json_save_var_color("leaves_spruce_color", env_leaves_spruce_color)
		json_save_var_color("leaves_birch_color", env_leaves_birch_color)
		json_save_var_color("leaves_jungle_color", env_leaves_jungle_color)
		json_save_var_color("leaves_acacia_color", env_leaves_acacia_color)
		json_save_var_color("leaves_dark_oak_color", env_leaves_dark_oak_color)
		json_save_var_color("leaves_mangrove_color", env_leaves_mangrove_color)
		
		json_save_var_bool("fog_show", env_fog_show)
		json_save_var_bool("fog_sky", env_fog_sky)
		json_save_var_bool("fog_color_custom", env_fog_color_custom)
		json_save_var_color("fog_color", env_fog_color)
		json_save_var_bool("fog_object_color_custom", env_fog_custom_object_color)
		json_save_var_color("fog_object_color", env_fog_object_color)
		json_save_var("fog_distance", env_fog_distance)
		json_save_var("fog_size", env_fog_size)
		json_save_var("fog_height", env_fog_height)
		
		json_save_var_bool("wind", env_wind)
		json_save_var("wind_speed", env_wind_speed)
		json_save_var("wind_strength", env_wind_strength)
		json_save_var("wind_direction", env_wind_direction)
		json_save_var("wind_directional_speed", env_wind_directional_speed)
		json_save_var("wind_directional_strength", env_wind_directional_strength)
		
		json_save_var("texture_animation_speed", env_texture_animation_speed)
		json_save_var("brightness", env_brightness)
		
	json_save_object_done()
}
