#include "CppGen.hpp"

namespace CppGen
{
void CodeWriter::begin(String indentation)
{
	CodeWriter::builder = StringBuilder("");
	CodeWriter::indentLevel = 0;
	CodeWriter::indented = false;
	CodeWriter::indentString = indentation;
	CodeWriter::lines = 0;

	writeLine("/*", 1);
	writeLine("NOTE:");
	writeLine("This file was autogenerated by CppGen, changes may be overwritten and forever lost!");
	writeLine("Modify at your own risk!");
	writeLine();
	writeLine("[ Generated on " + DateTime::now().toString("yyyy.MM.dd HH:mm:ss") + " ]");
	writeLine("*/", -1);
	writeLine();
}

void CodeWriter::write(const String& code)
{
	writeIndent();
	CodeWriter::builder.append(code);
	CodeWriter::isNewLine = false;
}

void CodeWriter::writeLine(const String& code, int indentDelta)
{
	if (indentDelta < 0)
		indent(-1);
	writeIndent();

	CodeWriter::builder.appendLine(code);
	CodeWriter::indented = false;
	CodeWriter::lines++;
	CodeWriter::isNewLine = true;

	if (indentDelta > 0)
		indent(1);
}

void CodeWriter::erase(int characters)
{
	CodeWriter::builder.remove(CodeWriter::builder.size() - characters, characters);
}

void CodeWriter::indent(int delta)
{
	CodeWriter::indentLevel += delta;
}

void CodeWriter::end(String outputFile)
{
	try
	{
		String code = CodeWriter::builder.toString();
		if (File::exists(outputFile)) // Check for difference (except timestamp)
		{
			String codeNoTimestamp = Regex::replace(code, "\\[ Generated on .*? \\]", "");
			String oldCodeNoTimestamp = Regex::replace(File::readAllText(outputFile), "\\[ Generated on .*? \\]", "");
			if (codeNoTimestamp == oldCodeNoTimestamp)
				return;
		}
		File::writeAllText(outputFile, code);
		CodeWriter::totalLines += CodeWriter::lines;
		CodeWriter::totalFilesUpdated++;
	}
	catch (const std::exception& ex)
	{
		Console::writeLine("FATAL ERROR: " + String(ex.what()));
		std::exit(1);
	}
}

void CodeWriter::writeIndent()
{
	if (CodeWriter::indented)
		return;

	for (int i = 0; i < CodeWriter::indentLevel; i++)
		CodeWriter::builder.append(CodeWriter::indentString);
	CodeWriter::indented = true;
}

}
