#include "CppGen.hpp"

int main(int argc, char** argv)
{
	return CppGen::Program::main(argc, argv);
}

namespace CppGen
{

OrderedMap<DataType*> Program::varTypeOverride;

int Program::main(int argc, char** argv)
{
	// Parse arguments
	String repoRootDir = argc > 1
		? argv[1]
		: fsString(fs::current_path().parent_path().parent_path());

	String gmlSpecFile = argc > 2
		? argv[2]
		: fsString(fs::current_path().parent_path()) + "/gml.json";

	bool assetsManifest = (argc > 3 && String(argv[3]) == "--assets-manifest");

	String gmDir = repoRootDir + "/GmProject";
	if (DirectoryInfo(gmDir).getFiles("*.yyp").size() == 0)
	{
		Console::writeLine("FATAL ERROR: No GameMaker project found in {0}", gmDir);
		std::exit(1);
	}

	if (!File::exists(gmlSpecFile))
	{
		Console::writeLine("FATAL ERROR: Could not find GML spec at {0}", gmlSpecFile);
		std::exit(1);
	}

	String outputDir = repoRootDir + "/CppProject/Generated";
	StringId::initialize();

	// Parse sprites
	List<String> spriteDirs = Directory::getDirectories(gmDir + "/sprites");
	for (String dir : spriteDirs)
	{
		Sprite* spr = makeObject<Sprite>(dir);
		Program::sprites.add(spr->name, spr);
	}

	// Parse shaders
	List<String> shaderDirs = Directory::getDirectories(gmDir + "/shaders");
	for (String dir : shaderDirs)
	{
		Shader* shader = makeObject<Shader>(dir);
		if (shader->isValid)
			Program::shaders.add(shader->name, shader);
	}

	// Parse scripts
	List<String> scriptDirs = Directory::getDirectories(gmDir + "/scripts");
	for (String dir : scriptDirs)
	{
		Script* script = makeObject<Script>(dir);
		Program::scripts.add(script->name, script);
	}

	// Assets manifest file for CMake
	if (assetsManifest)
	{
		StringBuilder text;
		text.appendLine("# Auto-generated by CppGen; do not edit.");
		text.appendLine("set(CPPGEN_SPRITE_RESOURCE_ENTRIES");
		for (Sprite* sprite : Program::sprites.values)
		{
			for (int frameIndex = 0; frameIndex < sprite->numFrames; frameIndex++)
			{
				text.appendLine("\t\"GmProject/sprites/" + String(sprite->name) + "/" + sprite->frameNames[frameIndex]
					+ ".png|Sprites/" + String(sprite->name) + "_frame_" + frameIndex + ".png|" + sprite->gmPath + "\"");
			}
		}
		text.appendLine(")");
		text.appendLine();
		text.appendLine("set(CPPGEN_SHADER_RESOURCE_ENTRIES");
		for (Shader* shader : Program::shaders.values)
		{
			text.appendLine("\t\"GmProject/shaders/" + String(shader->name) + "/" + shader->name
				+ ".vsh|Shaders/" + shader->name + ".vsh|" + shader->gmPath + "\"");
			text.appendLine("\t\"GmProject/shaders/" + String(shader->name) + "/" + shader->name
				+ ".fsh|Shaders/" + shader->name + ".fsh|" + shader->gmPath + "\"");
		}
		text.appendLine(")");
		text.appendLine();
		text.appendLine("set(CPPGEN_SCRIPT_ENTRIES");
		for (Script* script : Program::scripts.values)
		{
			text.appendLine("\t\"GmProject/scripts/" + String(script->name) + "/" + script->name
				+ ".gml|" + script->gmPath + "\"");
		}
		text.appendLine(")");
		String outputFile = outputDir + "/Assets.cmake";
		String textStr = text.toString();
		if (!File::exists(outputFile) || File::readAllText(outputFile) != textStr)
		{
			File::writeAllText(outputFile, textStr);
			Console::writeLine("CppGen: Created assets manifest file");
		}
		return 0;
	}

	Console::writeLine("Mine-imator GML -> C++ conversion begin");
	Console::writeLine("Input project: " + gmDir);
	Console::writeLine("Scripts output folder: " + outputDir);
	const String cacheFile = outputDir + "/CppGen.cache";
	const String cacheFingerprint = getCacheFingerprint(repoRootDir, gmDir, gmlSpecFile);

	GML::parseGMLSpec(gmlSpecFile);
	Program::strings.add("");

	Stopwatch timer = Stopwatch();
	timer.start();

	// Parse script GML
	for (Script* script : Program::scripts.values)
		GML::parseGMLScript(script->filename);

	timer.stop();
	Console::writeLine("Parsed GML ({0} lines) in {1}ms", GML::totalLines, (int)timer.elapsed.totalMilliseconds);

	// Parse objects
	List<String> objectDirs = Directory::getDirectories(gmDir + "/objects");
	for (String dir : objectDirs)
	{
		Object* obj = makeObject<Object>(dir);
		Program::objects[obj->name] = obj;
	}

	if (!Program::objects.containsKey("app"))
	{
		Console::writeLine("FATAL ERROR: app object not found");
		std::exit(1);
	}

	// Create constructors/destructors for GM objects that call their event/destroy event functions
	for (Object* obj : Program::objects.values)
	{
		obj->setConstructor(makeObject<Function>(obj->name));
		Program::functions.add(obj->name, obj->constructor);
		if (obj->createFunction != nullptr && obj->name != STR(app))
		{
			Function::currentParseFunction = obj->constructor;
			obj->constructor->statements->addStatement(makeObject<CallStatement>(makeObject<Accessor>(obj->createFunction->name, List<Accessor::ArrayAccessor*>(), List<Expression*>(), nullptr, Token::Type::Unknown, 1), 1));
		}

		if (obj->destroyFunction != nullptr)
		{
			obj->setDestructor(makeObject<Function>(obj->name));
			Program::functions.add("~" + String(obj->name), obj->destructor);
			Function::currentParseFunction = obj->destructor;
			obj->destructor->statements->addStatement(makeObject<CallStatement>(makeObject<Accessor>(obj->destroyFunction->name, List<Accessor::ArrayAccessor*>(), List<Expression*>(), nullptr, Token::Type::Unknown, 1), 1));
		}
	}

	Program::objects["app"]->constructor->cppLinesBegin.add("global::_app = this;"); // Define global app pointer

	timer.restart();
	for (Function* func : Program::functions.values)
		func->parseTokens();
	timer.stop();
	Console::writeLine("Parsed tokens in {0}ms", (int)timer.elapsed.totalMilliseconds);

	if (Program::functions.containsKey("enums"))
		Program::functions.remove("enums");
	if (Program::functions.containsKey("macros"))
		Program::functions.remove("macros");

	// Resolve macros
	for (MacroStatement* macro : Program::macros.values)
		macro->resolve(ResolveScope(STR(global)));

	// Declare all globals found (empty type)
	for (DeclareStatement* declStmt : DeclareStatement::globalDeclarations)
		for (Declaration* decl : declStmt->declarations->declarations)
			declareVariable(STR(global), decl->name, DataType(), declStmt->func, Statement::Location(), declStmt->line);

	// Forced types
	varTypeOverride = {
		{ "build_pos", makeObject<DataType>(DataType::Type::Integer) },
		{ "build_pos_x", makeObject<DataType>(DataType::Type::Integer) },
		{ "build_pos_y", makeObject<DataType>(DataType::Type::Integer) },
		{ "build_pos_z", makeObject<DataType>(DataType::Type::Integer) },
		{ "build_size_x", makeObject<DataType>(DataType::Type::Integer) },
		{ "build_size_y", makeObject<DataType>(DataType::Type::Integer) },
		{ "build_size_z", makeObject<DataType>(DataType::Type::Integer) },
		{ "build_size_xy", makeObject<DataType>(DataType::Type::Integer) },
		{ "build_size_total", makeObject<DataType>(DataType::Type::Integer) },
		{ "build_single_stateid", makeObject<DataType>(DataType::Type::Integer) },
		{ "block_pos_x", makeObject<DataType>(DataType::Type::Integer) },
		{ "block_pos_y", makeObject<DataType>(DataType::Type::Integer) },
		{ "block_pos_z", makeObject<DataType>(DataType::Type::Integer) },
		{ "blockstartpos", makeObject<DataType>(DataType::Type::Integer) },
		{ "blockendpos", makeObject<DataType>(DataType::Type::Integer )}
	};

	timer.restart();
	List<String> modifiedGmlFiles;
	const bool loadedCache = loadResolverCache(cacheFile, cacheFingerprint, modifiedGmlFiles);
	bool hotReloaded = false;
	if (!loadedCache)
	{
		Console::writeLine("Resolving project");
		resolveProject();
		WithStatement::resolveUnknownScope =
		Accessor::resolveFunctionReferences =
		Accessor::resolveUnknownScope =
		Accessor::resolveUnknownMapTypes =
		Function::enableAssignScope =
		Program::mergeUnknownVars = true;
		resolveProject();
	}
	else if (modifiedGmlFiles.size() > 0)
	{
		WithStatement::resolveUnknownScope =
		Accessor::resolveFunctionReferences =
		Accessor::resolveUnknownScope =
		Accessor::resolveUnknownMapTypes =
		Function::enableAssignScope =
		Program::mergeUnknownVars = true;
		const int reloadedFunctions = hotReloadFunctions(modifiedGmlFiles);
		Console::writeLine("Hot reloaded {0} function(s) from {1} modified GML file(s)", reloadedFunctions, modifiedGmlFiles.size());
		hotReloaded = true;
	}
	timer.stop();

	if (loadedCache)
		Console::writeLine("Loaded cache in {0}ms", (int)timer.elapsed.totalMilliseconds);
	else
	{
		int percResolved = (int)((1.0f - Variable::variantVariables / (float)Variable::totalVariables) * 100.0f);
		Console::writeLine("Solved {0} out of {1} variable types ({2}%) in {3}ms", Variable::totalVariables - Variable::variantVariables, Variable::totalVariables, percResolved,(int)timer.elapsed.totalMilliseconds);
	}

	timer.restart();

	// Generate GmlFunc.hpp
	GML::exportHeader(outputDir + "/GmlFunc.hpp");

	// Generate Scripts.hpp
	CodeWriter::begin();
	CodeWriter::writeLine("#pragma once");
	CodeWriter::writeLine("#include \"GmlFunc.hpp\"");
	CodeWriter::writeLine();
	CodeWriter::writeLine("namespace CppProject");
	CodeWriter::writeLine("{", 1);

	for (MacroStatement* macroStmt : Program::macros.values)
		macroStmt->writeCpp(ResolveScope(STR(global)));
	CodeWriter::writeLine();

	for (EnumStatement* enumStmt : Program::enums.values)
	{
		enumStmt->writeCpp(ResolveScope(STR(global)));
		CodeWriter::writeLine();
	}

	CodeWriter::writeLine("struct app;");
	CodeWriter::writeLine("struct global");
	CodeWriter::writeLine("{", 1);
	CodeWriter::writeLine("static app* _app;");
	for (Variable* var : Program::globalVars.values)
		if (!Program::macros.containsKey(var->name))
			CodeWriter::writeLine("static " + var->type->toCpp() + " " + var->name + ";");
	CodeWriter::writeLine("};", -1);
	CodeWriter::writeLine();

	for (Object* obj : Program::objects.values)
	{
		obj->writeCppHeader();
		CodeWriter::writeLine();
	}

	for (Function* func : Program::functions.values)
		if (func->structObject == nullptr)
			func->writeCppHeader();

	DataType::ignoreAllVarType = true;
	if (Program::externalFunctions.size() > 0)
		CodeWriter::writeLine();
	for (ExternalFunction* extFunc : Program::externalFunctions.values)
		extFunc->writeCppHeader();
	DataType::ignoreAllVarType = false;

	int assetId = 20;
	CodeWriter::writeLine();
	for (Object* obj : Program::objects.values)
		CodeWriter::writeLine("#define ID_" + String(obj->name) + " IntType(" + (assetId++) + ")");

	CodeWriter::writeLine();
	for (Sprite* sprite : Program::sprites.values)
		CodeWriter::writeLine("#define ID_" + String(sprite->name) + " IntType(" + (assetId++) + ")");

	CodeWriter::writeLine();
	for (Shader* shader : Program::shaders.values)
		CodeWriter::writeLine("#define ID_" + String(shader->name) + " IntType(" + (assetId++) + ")");

	CodeWriter::writeLine();
	for (Function* func : Program::functions.values)
		if (func->structObject == nullptr)
			CodeWriter::writeLine("#define ID_" + String(func->name) + " IntType(" + (assetId++) + ")");

	List<String> members = List<String>();
	for (Object* obj : Program::objects.values)
	{
		for (StringId varName : obj->instanceVars.keys)
		{
			String cppName = CodeObject::nameToCpp(varName);
			if (!members.contains(cppName))
				members.add(cppName);
		}
		for (StringId funcName : obj->instanceFunctions.keys)
		{
			String cppName = CodeObject::nameToCpp(funcName);
			if (!members.contains(cppName))
				members.add(cppName);
		}
	}

	for (StringId varName : Program::unknownScopeVars.keys)
	{
		String cppName = CodeObject::nameToCpp(varName);
		if (!members.contains(cppName))
			members.add(cppName);
	}

	assetId = 0;
	members.sort();
	CodeWriter::writeLine();
	for (String mem : members)
		CodeWriter::writeLine("#define M_" + mem + " IntType(" + (assetId++) + ")");

	CodeWriter::writeLine();

	CodeWriter::writeLine("}", -1);
	CodeWriter::end(outputDir + "/Scripts.hpp");

	// Declare Globals.cpp
	CodeWriter::begin();
	CodeWriter::writeLine("#include \"Scripts.hpp\"");
	CodeWriter::writeLine("#include \"Asset/Shader.hpp\"");
	CodeWriter::writeLine();
	CodeWriter::writeLine("namespace CppProject");
	CodeWriter::writeLine("{", 1);

	DataType::ignoreAllVarType = true;
	for (StringId var : GML::variables.keys)
		if (!GML::keywords.contains(var) && var != STR(argument) && var != STR(argument_count))
			CodeWriter::writeLine(GML::variables[var]->toCpp() + " gmlGlobal::" + var + " = " + GML::variables[var]->toCppDefaultValue() + ";");
	CodeWriter::writeLine();
	DataType::ignoreAllVarType = false;

	CodeWriter::writeLine("app* global::_app = nullptr;");
	for (Variable* var : Program::globalVars.values)
		if (!Program::macros.containsKey(var->name))
			CodeWriter::writeLine(var->type->toCpp() + " global::" + var->name + " = " + var->type->toCppDefaultValue() + ";");
	CodeWriter::writeLine();

	CodeWriter::writeLine("}", -1);
	CodeWriter::end(outputDir + "/Globals.cpp");

	// Generate Scripts1...n.cpp
	const int maxLinePerFile = 1000;
	int existingScriptFiles = 0;
	if (hotReloaded)
	{
		while (FileInfo(outputDir + "/Scripts" + (existingScriptFiles + 1) + ".cpp").exists)
			existingScriptFiles++;
	}

	int f = 1;
	while (!hotReloaded || f <= existingScriptFiles)
	{
		const bool finalScriptFile = hotReloaded && f == existingScriptFiles;
		CodeWriter::begin();
		CodeWriter::writeLine("#include \"Scripts.hpp\"");
		CodeWriter::writeLine();
		CodeWriter::writeLine("namespace CppProject");
		CodeWriter::writeLine("{", 1);

		for (Object* obj : Program::objects.values)
		{
			obj->writeCppImplementation();
			if (!finalScriptFile && CodeWriter::lines > maxLinePerFile)
				break;
		}

		int funcWritten = 0;
		if (finalScriptFile || CodeWriter::lines <= maxLinePerFile)
		{
			for (Function* func : Program::functions.values)
			{
				if (func->structObject != nullptr || func->isCppSeparate)
					continue;

				if (func->writeCppImplementation())
					funcWritten++;

				if (!finalScriptFile && CodeWriter::lines > maxLinePerFile)
					break;
			}

			if (!hotReloaded && funcWritten == 0)
				break; // Don't generate final file
		}

		CodeWriter::writeLine("}", -1);
		CodeWriter::end(outputDir + "/Scripts" + f + ".cpp");
		f++;
	}

	// Delete unused
	while (true)
	{
		FileInfo file = FileInfo(outputDir + "/Scripts" + f + ".cpp");
		if (file.exists)
			file.deleteFile();
		else
			break;
		f++;
	}

	// Generate Assets.cpp
	CodeWriter::begin();
	CodeWriter::writeLine("#include \"Asset/Script.hpp\"");
	CodeWriter::writeLine("#include \"Asset/Shader.hpp\"");
	CodeWriter::writeLine("#include \"Asset/Sprite.hpp\"");
	CodeWriter::writeLine("#include \"Scripts.hpp\"");
	CodeWriter::writeLine();
	CodeWriter::writeLine("#define AddSprite(name, numFrames, originX, originY) \\", 1);
	CodeWriter::writeLine("new Sprite(#name, ID_##name, numFrames, { originX, originY });");
	CodeWriter::indent(-1);
	CodeWriter::writeLine();
	CodeWriter::writeLine("#define AddShader(name) \\", 1);
	CodeWriter::writeLine("new Shader(#name, ID_##name);");
	CodeWriter::indent(-1);
	CodeWriter::writeLine();
	CodeWriter::writeLine("#define AddScript(name, ...) \\", 1);
	CodeWriter::writeLine("{ #name, ID_##name, +[](IntType s, IntType o, VarArgs a) -> VarType __VA_ARGS__ },");
	CodeWriter::indent(-1);
	CodeWriter::writeLine();
	CodeWriter::writeLine("namespace CppProject");
	CodeWriter::writeLine("{", 1);
	CodeWriter::writeLine("void Asset::Load()");
	CodeWriter::writeLine("{", 1);

	for (Sprite* spr : Program::sprites.values)
		CodeWriter::writeLine("AddSprite(" + String(spr->name) + ", " + String(spr->numFrames) + ", " + String(spr->originX) + ", " + String(spr->originY) + ");");

	CodeWriter::writeLine();
	for (Shader* shader : Program::shaders.values)
		CodeWriter::writeLine("AddShader(" + String(shader->name) + ");");

	CodeWriter::writeLine();
	CodeWriter::writeLine("struct ScriptDefinition");
	CodeWriter::writeLine("{", 1);
	CodeWriter::writeLine("const char* name;");
	CodeWriter::writeLine("IntType id;");
	CodeWriter::writeLine("Script::ExecuteFunction function;");
	CodeWriter::writeLine("};", -1);
	CodeWriter::writeLine();
	CodeWriter::writeLine("static const ScriptDefinition scripts[] =");
	CodeWriter::writeLine("{", 1);
	for (Function* func : Program::functions.values)
		if (func->structObject == nullptr && !String(func->name).startsWith("builder_add_"))
			CodeWriter::writeLine("AddScript(" + String(func->name) + ", " + func->toExecuteCpp() + ")");
	CodeWriter::writeLine("};", -1);
	CodeWriter::writeLine();
	CodeWriter::writeLine("for (const ScriptDefinition& script : scripts)", 1);
	CodeWriter::writeLine("new Script(script.name, script.id, script.function);");
	CodeWriter::indent(-1);

	CodeWriter::writeLine("}", -1);
	CodeWriter::writeLine("}", -1);
	CodeWriter::end(outputDir + "/Assets.cpp");

	// Generate Objects1...n.cpp, splitting only between InitMembers() methods
	List<Object*> mappedObjects = List<Object*>(Program::objects.values);
	int mappedObject = 0;
	int objectFile = 1;
	while (mappedObject < static_cast<int>(mappedObjects.size()))
	{
		CodeWriter::begin();
		CodeWriter::writeLine("#include \"Scripts.hpp\"");
		CodeWriter::writeLine();
		CodeWriter::writeLine("#define DefineObjectMember(subAssetId, memberId, member, enumType) \\", 1);
		CodeWriter::writeLine("memberMap[subAssetId][memberId] = { enumType, (long long)&member - (long long)this };");
		CodeWriter::indent(-1);
		CodeWriter::writeLine();
		CodeWriter::writeLine("#define DefineObjectFunction(subAssetId, funcId, ...) \\", 1);
		CodeWriter::writeLine("instanceFuncMap[funcId] = [&](VarArgs a) __VA_ARGS__;");
		CodeWriter::indent(-1);
		CodeWriter::writeLine();
		CodeWriter::writeLine("namespace CppProject");
		CodeWriter::writeLine("{", 1);

		do
		{
			mappedObjects[mappedObject++]->writeInitMembers();
		}
		while (mappedObject < static_cast<int>(mappedObjects.size()) && CodeWriter::lines <= maxLinePerFile);

		CodeWriter::writeLine("}", -1);
		CodeWriter::end(outputDir + "/Objects" + objectFile + ".cpp");
		objectFile++;
	}

	// Delete unused object mapping files left by an earlier, larger generation
	while (true)
	{
		FileInfo file = FileInfo(outputDir + "/Objects" + objectFile + ".cpp");
		if (file.exists)
			file.deleteFile();
		else
			break;
		objectFile++;
	}

	// Generate AddGMLStrings.cpp
	CodeWriter::begin();
	CodeWriter::writeLine("#include \"Type/StringType.hpp\"");
	CodeWriter::writeLine();
	CodeWriter::writeLine("namespace CppProject");
	CodeWriter::writeLine("{", 1);
	CodeWriter::writeLine("void StringType::AddGMLStrings()");
	CodeWriter::writeLine("{", 1);
	for (String str : Program::strings)
		CodeWriter::writeLine("Add(\"" + str + "\");");
	CodeWriter::writeLine("}", -1);
	CodeWriter::writeLine("}", -1);
	CodeWriter::end(outputDir + "/AddGMLStrings.cpp");

	// Finished
	timer.stop();
	Console::writeLine("Generated code ({0} lines) in {1}ms", CodeWriter::totalLines, (int)timer.elapsed.totalMilliseconds);
	Console::writeLine("{0} file" + String(CodeWriter::totalFilesUpdated == 1 ? " was" : "s were") + " updated", CodeWriter::totalFilesUpdated);
	if (Program::syntaxErrors.empty() && (!loadedCache || hotReloaded))
	{
		timer.restart();
		bool cacheSaved = saveResolverCache(cacheFile, cacheFingerprint);
		timer.stop();
		if (cacheSaved)
			Console::writeLine("Saved resolved classes and types to cache in {0}ms", (int)timer.elapsed.totalMilliseconds);
	}

	if (Program::syntaxErrors.size() > 0)
	{
		for (String err : Program::syntaxErrors)
			Console::writeLine("ERROR: " + err);
		Console::writeLine(String("Finished with ") + Program::syntaxErrors.size() + " errors");
	}
	else
		Console::writeLine("Success!");

	return Program::syntaxErrors.empty() ? 0 : 1;
}

Shader::Shader(String dir)
{
	DirectoryInfo dirInfo = DirectoryInfo(dir);
	this->name = dirInfo.name;

	FileInfo srcVs = FileInfo(dir + "/" + this->name + ".vsh");
	FileInfo srcFs = FileInfo(dir + "/" + this->name + ".fsh");
	if (!srcVs.exists || !srcFs.exists)
		return;

	this->isValid = true;

	String json = File::readAllText(dir + "/" + dirInfo.name + ".yy");
	Json root = JsonConvert::deserializeObject(json);

	this->gmPath = root["parent"]["path"];
	this->gmPath = this->gmPath
		.replace("folders/Shaders.yy", "")
		.replace("folders/Shaders/", "")
		.replace(".yy", "");
}

Sprite::Sprite(String dir)
{
	DirectoryInfo dirInfo = DirectoryInfo(dir);
	this->name = dirInfo.name;

	String json = File::readAllText(dir + "/" + dirInfo.name + ".yy");
	Json root = JsonConvert::deserializeObject(json);

	this->originX = root["sequence"]["xorigin"];
	this->originY = root["sequence"]["yorigin"];
	this->gmPath = root["parent"]["path"];
	this->gmPath = this->gmPath
		.replace("folders/Sprites.yy", "")
		.replace("folders/Sprites/", "")
		.replace(".yy", "");

	for (Json frameObj : root["frames"])
	{
		String frameName = frameObj["name"];
		this->frameNames.add(frameName);
		this->numFrames++;
	}
}

Script::Script(String dir)
{
	DirectoryInfo dirInfo = DirectoryInfo(dir);
	this->name = dirInfo.name;
	this->filename = dir + "/" + dirInfo.name + ".gml";

	String json = File::readAllText(dir + "/" + dirInfo.name + ".yy");
	Json root = JsonConvert::deserializeObject(json);

	this->gmPath = root["parent"]["path"];
	this->gmPath = this->gmPath
		.replace("folders/Scripts.yy", "")
		.replace("folders/Scripts/", "")
		.replace(".yy", "");
}

void Program::resolveProject()
{
	// Mark unresolved
	for (Function* func : Program::functions.values)
		func->scopesTraversed.clear();
	for (Object* obj : Program::objects.values)
		for (Function* func : obj->instanceFunctions.values)
			func->scopesTraversed.clear();

	CodeObject::unknownScopes = 0;
	Program::unknownScopeVars.clear();
	Console::writeLine("Processing types...");

	while (true)
	{
		int passVariants = Variable::variantVariables;
		for (Function* func : Program::functions.values)
			func->isTraversed = false;
		for (Object* obj : Program::objects.values)
			for (Function* func : obj->instanceFunctions.values)
				func->isTraversed = false;

		// Resolve object constructors/destructors
		for (Object* obj : Program::objects.values)
		{
			if (obj->name == STR(app))
				continue;

			if (obj->constructor != nullptr)
				obj->constructor->resolve(ResolveScope(obj->name));

			if (obj->destructor != nullptr)
				obj->destructor->resolve(ResolveScope(obj->name));
		}

		Program::objects[STR(app)]->constructor->resolve(ResolveScope(STR(app)));

		// Resolve app functions
		if (Program::appDrawFunction != nullptr)
			Program::appDrawFunction->resolve(ResolveScope(STR(app)));
		if (Program::appStepFunction != nullptr)
			Program::appStepFunction->resolve(ResolveScope(STR(app)));
		if (Program::appHttpFunction != nullptr)
			Program::appHttpFunction->resolve(ResolveScope(STR(app)));
		if (Program::appGameEndFunction != nullptr)
			Program::appGameEndFunction->resolve(ResolveScope(STR(app)));

		// Resolve instance functions
		for (Object* obj : Program::objects.values)
			for (Function* func : obj->instanceFunctions.values)
				func->resolve(ResolveScope(obj->name));

		if (Program::mergeUnknownVars)
		{
			// Merge instance variables with other instance variables of same name declared in the same function scope
			for (Function* func : Program::functions.values)
			{
				for (int v = 0; v < static_cast<int>(func->instanceVarDecls.size()); v++)
				{
					Variable* v1 = func->instanceVarDecls[v];
					for (int vv = 0; vv < static_cast<int>(func->instanceVarDecls.size()); vv++)
					{
						if (v == vv)
							continue;

						Variable* v2 = func->instanceVarDecls[vv];
						if (v2->name == v1->name)
							v2->type->assign(*v1->type, func, 0);
					}
				}
			}

			// Merge unknown variables with instnace variables of same name
			for (Variable* unknownVar : Program::unknownScopeVars.values)
			{
				// Apply instance variables to unknown
				for (Object* obj : Program::objects.values)
					for (Variable* instVar : obj->instanceVars.values)
						if (unknownVar->name == instVar->name)
							unknownVar->assignType(*instVar->type, nullptr, 0);

				// Apply unknown variables to instances
				for (Object* obj : Program::objects.values)
					for (Variable* instVar : obj->instanceVars.values)
						if (unknownVar->name == instVar->name)
							instVar->assignType(*unknownVar->type, nullptr, 0);
			}
		}

		// Nothing was changed, break pass
		if (Variable::variantVariables == passVariants)
			break;
	}

	// Resolve unused functions in any scope
	if (Accessor::resolveFunctionReferences)
	{
		for (Function* func : Program::functions.values)
		{
			if (func->isUnused)
			{
				// Ensure scope is correct for block scripts
				if (String(func->name).startsWith("block_set_") || String(func->name).startsWith("block_tile_entity_"))
					func->resolve(ResolveScope(STR(obj_builder_thread)));
				else
					func->resolve(ResolveScope(STR(any)));
			}
		}
	}
}

int Program::hotReloadFunctions(const List<String>& modifiedGmlFiles)
{
	Program::hotReloading = true;
	Program::hotReloadTargets.clear();
	for (Function* function : Program::functions.values)
		if (function->sourceFile != "" && modifiedGmlFiles.contains(function->sourceFile))
			Program::hotReloadTargets.add(function);

	int reloaded = 0;
	for (Function* function : Program::hotReloadTargets)
	{
		List<StringId> previousScopes;
		for (Function::ScopeAssignment* assignment : function->scopeAssignments)
			previousScopes.add(assignment->scope);
		const StringId previousScope = function->getScope();

		if (function->args != nullptr)
			for (Declaration* declaration : function->args->declarations)
				for (Variable* variable : function->vars)
					if (variable->line == 0 && variable->name == declaration->name)
						declaration->isReference = variable->isReference;
		if (previousScopes.size() == 0)
			function->resolve(ResolveScope(previousScope));
		else
			for (StringId scope : previousScopes)
				function->resolve(ResolveScope(scope));
		reloaded++;
	}
	Program::hotReloadTargets.clear();
	Program::hotReloading = false;
	return reloaded;
}

Variable* Program::findVariable(StringId scope, StringId name, Function* func, const Statement::Location& location, int line, Function* funcAssignScope, bool includeUnknown)
{
	// Local or argument
	if (func != nullptr)
	{
		for (int i = func->vars.size() - 1; i >= 0; i--)
		{
			Variable* var = func->vars[i];
			if (var->name == name && var->location.contains(location)) // Name must match and be declared outside this location
			{
				if (var->line == 0 && func->varArgs && !func->varArgsRequiredNames.contains(name))
					func->varArgsRequiredNames.add(name);
				return var;
			}
		}

		// argument0..15
		if (name.id() >= STR(argument0) && name.id() <= STR(argument15))
		{
			int argNum = name.id() - STR(argument0);
			if (argNum >= 0 && static_cast<int>(func->vars.size()) > argNum && func->vars[argNum]->line == 0)
				return func->vars[argNum];
		}
	}

	// Unknown scope
	if (scope == STR(any) && includeUnknown && Program::unknownScopeVars.containsKey(name))
	{
		if (funcAssignScope != nullptr)
			funcAssignScope->assignScope(scope, func, line, true);
		return Program::unknownScopeVars[name];
	}

	// Instance (scope is object name)
	if (Program::objects.containsKey(scope))
	{
		if (Program::objects[scope]->instanceVars.containsKey(name))
		{
			Variable* var = Program::objects[scope]->instanceVars[name];
			if (funcAssignScope != nullptr)
			{
				if (!funcAssignScope->instanceVarDecls.contains(var)) // Add variable to function
					funcAssignScope->instanceVarDecls.add(var);
				funcAssignScope->assignScope(scope, func, line, true);
			}
			return var;
		}
	}

	// Global
	if (Program::globalVars.containsKey(name))
		return Program::globalVars[name];

	return nullptr;
}

Variable* Program::declareVariable(StringId scope, StringId name, const DataType& type, Function* func, const Statement::Location& location, int line, Function* funcAssignScope)
{
	// Unknown scope
	if (scope == STR(any))
	{
		if (!Program::unknownScopeVars.containsKey(name))
			Program::unknownScopeVars.add(name, makeObject<Variable>(scope, name, type, line, location));
		else
			Program::unknownScopeVars[name]->assignType(type, func, line);
		if (funcAssignScope != nullptr)
			funcAssignScope->assignScope(scope, func, line, true);
		return Program::unknownScopeVars[name];
	}

	// Global
	if (scope == STR(global))
	{
		if (!Program::globalVars.containsKey(name))
			Program::globalVars.add(name, makeObject<Variable>(scope, name, type, line, location));
		else
			Program::globalVars[name]->assignType(type, func, line);

		return Program::globalVars[name];
	}

	// Instance (scope is object name, and this is not an argument)
	if (Program::objects.containsKey(scope) && line > 0)
	{
		if (!Program::objects[scope]->instanceVars.containsKey(name))
			Program::objects[scope]->instanceVars.add(name, makeObject<Variable>(scope, name, type, line, location));
		else
			Program::objects[scope]->instanceVars[name]->assignType(type, func, line);

		Variable* var = Program::objects[scope]->instanceVars[name];
		if (funcAssignScope != nullptr)
		{
			if (!funcAssignScope->instanceVarDecls.contains(var)) // Add variable to function
				funcAssignScope->instanceVarDecls.add(var);
			funcAssignScope->assignScope(scope, func, line, true);
		}
		return var;
	}

	// Local (scope is function name)
	if (func != nullptr)
	{
		for (Variable* var : func->vars)
		{
			if (var->name != name)
				continue;

			if (var->line == line)  // Update pre-declared variable
			{
				var->assignType(type, func, line);
				return var;
			}
			else if (var->location.equals(location)) // Redeclared in the same scope
			{
				addSyntaxError("Variable " + String(name) + " redeclared, previous on line " + var->line + " in " + String(func->name) + ":" + line);
				return var;
			}
		}

		Variable* newVar = makeObject<Variable>(scope, name, type, line, location);
		func->vars.add(newVar);
		return newVar;
	}

	return nullptr;
}

void Program::addSyntaxError(String text)
{
	if (!Program::syntaxErrors.contains(text))
		Program::syntaxErrors.add(text);
}

}
