#pragma once

namespace CppGen
{
#define PREDEFINED_STRINGS \
	ADD(global) \
	ADD(any) \
	ADD(app) \
	ADD(id) \
	ADD(self) \
	ADD(other) \
	ADD(object_index) \
	ADD(undefined) \
	ADD(new_obj) \
	ADD(array_add) \
	ADD(array) \
	ADD(argument) \
	ADD(argument_count) \
	ADD(argument0) \
	ADD(argument1) \
	ADD(argument2) \
	ADD(argument3) \
	ADD(argument4) \
	ADD(argument5) \
	ADD(argument6) \
	ADD(argument7) \
	ADD(argument8) \
	ADD(argument9) \
	ADD(argument10) \
	ADD(argument11) \
	ADD(argument12) \
	ADD(argument13) \
	ADD(argument14) \
	ADD(argument15) \
	ADD(obj_builder_thread) \
	ADD(gml_pragma) \
	ADD(external_define) \
	ADD(ty_real) \
	ADD(function) \
	ADD(constructor) \
	ADD(div) \
	ADD(mod) \
	ADD(case) \
	ADD(default) \
	ADD(else) \
	ADD(until) \
	ADD(macro) \
	ADD(enums) \
	ADD(var) \
	ADD(globalvar) \
	ADD(if) \
	ADD(while) \
	ADD(do) \
	ADD(for) \
	ADD(repeat) \
	ADD(with) \
	ADD(switch) \
	ADD(return) \
	ADD(break) \
	ADD(continue) \
	ADD(enum) \
	ADD(delete) \
	ADD(static) \
	ADD(region) \
	ADD(endregion) \
	ADD(new) \
	ADD(unknown) \
	ADD(VarType) \
	ADD(variant) \
	ADD(null) \
	ADD(void) \
	ADD(BoolType) \
	ADD(bool) \
	ADD(intorreal) \
	ADD(IntType) \
	ADD(int) \
	ADD(RealType) \
	ADD(real) \
	ADD(StringType) \
	ADD(string) \
	ADD(reference) \
	ADD(VecType) \
	ADD(vec) \
	ADD(MatrixType) \
	ADD(matrix) \
	ADD(ArrType) \
	ADD(list) \
	ADD(anymap) \
	ADD(intmap) \
	ADD(stringmap) \
	ADD(map) \
	ADD(grid) \
	ADD(stack) \
	ADD(priority) \
	ADD(Unknown) \
	ADD(Variant) \
	ADD(Null) \
	ADD(Void) \
	ADD(Bool) \
	ADD(IntOrReal) \
	ADD(Integer) \
	ADD(Real) \
	ADD(String) \
	ADD(Reference) \
	ADD(Array) \
	ADD(Vector) \
	ADD(Matrix) \
	ADD(List) \
	ADD(AnyMap) \
	ADD(IntMap) \
	ADD(StringMap) \
	ADD(Map) \
	ADD(Grid) \
	ADD(Stack) \
	ADD(Priority) \
	ADD(save_id_find) \
	ADD(ds_int_map_create) \
	ADD(ds_string_map_create) \
	ADD(json_load) \
	ADD(test) \
	ADD(array_create) \
	ADD(array_length) \
	ADD(choose) \
	ADD(max) \
	ADD(min) \
	ADD(ds_list_add) \
	ADD(ds_map_find_first) \
	ADD(ds_map_find_next) \
	ADD(ds_map_find_value) \
	ADD(ds_map_add) \
	ADD(ds_stack_push) \
	ADD(ds_grid_set) \
	ADD(ds_grid_get) \
	ADD(ds_list_copy) \
	ADD(ds_map_copy) \
	ADD(shader_set_uniform_f) \
	ADD(shader_set_uniform_i) \
	ADD(external_call) \
	ADD(ord) \
	ADD(current_time) \
	ADD(ds_map_create) \
	ADD(MAT_X) \
	ADD(MAT_Y) \
	ADD(MAT_Z) \
	ADD(block_size) \
	ADD(char) \
	ADD(double) \
	ADD(export) \
	ADD(far) \
	ADD(float) \
	ADD(inline) \
	ADD(interface) \
	ADD(near) \
	ADD(NULL) \
	ADD(pi) \
	ADD(sample_rate) \
	ADD(slots) \
	ADD(small) \
	ADD(template) \
	ADD(typename) \
	ADD(subAssetId) \
	ADD(W) \
	ADD(X) \
	ADD(Y) \
	ADD(Z)

enum Strings : int
{
	Empty = 0,
#define ADD(name) str_##name,
	PREDEFINED_STRINGS
#undef ADD
	NextId
};

#define STR(name) Strings::str_##name
} // namespace CppGen