/// settings_save_colors()

json_save_object_start("colors")

	json_save_var_color("interface", setting_color_interface)
	json_save_var_color("background", setting_color_background)
	json_save_var_color("background_scrollbar", setting_color_background_scrollbar)
	json_save_var_color("text", setting_color_text)
	json_save_var_color("tips", setting_color_tips)
	json_save_var_color("tips_text", setting_color_tips_text)
	json_save_var_color("buttons", setting_color_buttons)
	json_save_var_color("buttons_pressed", setting_color_buttons_pressed)
	json_save_var_color("buttons_text", setting_color_buttons_text)
	json_save_var_color("boxes", setting_color_boxes)
	json_save_var_color("boxes_pressed", setting_color_boxes_pressed)
	json_save_var_color("boxes_text", setting_color_boxes_text)
	json_save_var_color("highlight", setting_color_highlight)
	json_save_var_color("highlight_text", setting_color_highlight_text)
	json_save_var_color("timeline", setting_color_timeline)
	json_save_var_color("alerts", setting_color_alerts)
	json_save_var_color("alerts_text", setting_color_alerts_text)
	json_save_var_color("timeline_text", setting_color_timeline_text)
	json_save_var_color("timeline_select", setting_color_timeline_select)
	json_save_var_color("timeline_marks", setting_color_timeline_marks)
	json_save_var_color("timeline_select_box", setting_color_timeline_select_box)
	json_save_var_color("viewport_selection", setting_color_viewport_selection)

json_save_object_done()