/// settings_load_legacy_colors()

/*setting_color_interface = */ buffer_read_int()
/*setting_color_background = */ buffer_read_int()
/*setting_color_background_scrollbar = */ buffer_read_int()
/*setting_color_text = */ buffer_read_int()
/*setting_color_tips = */ buffer_read_int()
/*setting_color_tips_text = */ buffer_read_int()
/*setting_color_buttons = */ buffer_read_int()
/*setting_color_buttons_pressed = */ buffer_read_int()
/*setting_color_buttons_text = */ buffer_read_int()
/*setting_color_boxes = */ buffer_read_int()
/*setting_color_boxes_pressed = */ buffer_read_int()
/*setting_color_boxes_text = */ buffer_read_int()
/*setting_color_highlight = */ buffer_read_int()
/*setting_color_highlight_text = */ buffer_read_int()
/*setting_color_timeline = */ buffer_read_int()
/*setting_color_timeline_text = */ buffer_read_int()
/*setting_color_timeline_select = */ buffer_read_int()
/*setting_color_alerts = */ buffer_read_int()
/*setting_color_alerts_text = */ buffer_read_int()
